challenge2/challenge2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('chat/', include('chat.urls')),
    path('admin/', admin.site.urls),
]

challenge2/chat/urls.py
from django.urls import path, include
from . import views


app_name = 'chat'
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.createChat, name="create"),
    path('enter/', views.enterChat, name="enter"),
    path('room/<id>', views.room, name="room"),
    path('getStuffFromCollection/', views.getStuffFromCollection.as_view(), name="stuff"),
    path('getStuffFromCollection/<message>', views.getStuffFromCollection.as_view(), name="addStuff"),
]

challenge2/restFramework/urls.py
from django.urls import path
from . import views
'''
urlpatterns = [
    path('getStuffFromCollection', views.getStuffFromCollection.as_view, name="stuff"),
]
'''

challenge2/chat/models.py
from django.db import models

# Create your models here.

challenge2/restFramework/models.py
from django.db import models

# Create your models here.

challenge2/chat/forms.py
from django import forms

class PinForm(forms.Form):
    pin = forms.IntegerField()


class CreateRoomForm(forms.Form):
    name = forms.CharField()
    pin = forms.IntegerField()

class CreateMessageForm(forms.Form):
    message = forms.CharField()

challenge2/chat/views.py
from django.shortcuts import render,redirect, reverse
from pymongo import MongoClient, DESCENDING
from bson.objectid import ObjectId
from .forms import PinForm, CreateRoomForm, CreateMessageForm
from django.http import HttpResponse, JsonResponse
from rest_framework.renderers import JSONRenderer
from django.views.decorators.csrf import csrf_exempt
from bson.json_util import dumps
from rest_framework import status, views
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import serializers
from rest_framework.decorators import api_view
from pprint import pprint
import datetime

client = MongoClient('localhost', 27017)
db = client.test
chat_room_collection = db.chatRoom
messagesCollection = db.messages


#JsonResponse(dumps(list(messages.find({'name':'Shannon Brown'}))),safe=
#    ...: False)

# Create your views here.
def index(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = PinForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            chat = chat_room_collection.find_one({'pin': form.cleaned_data['pin']})
            #print('pin : ' + str(form.cleaned_data['pin']))
            chatID = chat['_id']
            #print(chat_room_collection.find_one({'pin': str(form.cleaned_data['pin'])})['_id'])
            #chatID = chat['_id']
            # redirect to a new URL:
            return redirect(reverse('chat:room', kwargs={'id':chatID}))
            #return render(request, 'chat/room.html', {'pin': form.cleaned_data['pin']})

    # if a GET (or any other method) we'll create a blank form
    else:
        form = PinForm()

    return render(request, 'chat/index.html', {'form': form})



def createChat(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = CreateRoomForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            name = form.cleaned_data['name']
            pin = form.cleaned_data['pin']
            chat_room_collection.insert({'name': name, 'pin': pin})
            # redirect to a new URL:
            return redirect(reverse('chat:room', kwargs={'pin':pin}))

    # if a GET (or any other method) we'll create a blank form
    else:
        form = CreateRoomForm()

    return render(request, 'chat/create.html', {'form':form})

def enterChat(request):
    pin = chat_room_collection.find({'pin': '1234'})
    context = {'collection': pin}
    return render(request, 'chat/enter.html', context)

def room(request, id):
    #print(pin)
    chatName = chat_room_collection.find_one({'_id': ObjectId(id)})['name']
    messages = messagesCollection.find({'room': ObjectId(id)}).sort("timestamp", DESCENDING)
    context = {
        'name':chatName,
        'messages':messages,
        'id': id,
    }


    return render(request, 'chat/room.html', context)

class getStuffFromCollection(APIView):
    def get(self, request, format=None):
        messages = messagesCollection.find({'room': ObjectId(request.GET.get("room"))}).sort("timestamp", 1)
        newMessages = []
        for message in messages:
            message.pop('_id')
            message.pop('room')
            newMessages.append(message)
        return Response({'thingINeed':newMessages}, status=status.HTTP_200_OK)

    def post(self, request, format=None):
        x = messagesCollection.insert_one({"name": request.POST.get("name"), "message": request.POST.get("message"), "timestamp": datetime.datetime.now(), "room": ObjectId(request.POST.get("room"))})
        return Response({'status':"success","message": request.POST.get("message")}, status=status.HTTP_200_OK)

'''@api_view(['GET', 'POST'])
def hello_world(request):
    myclient = MongoClient("mongodb://localhost:27017/")
    mydb = myclient["test"]
    mycol = mydb["messages"]
    x = mycol.find_one()
    x["id"] = str(x["id"])

    return Response({'message':x}, status=status.HTTP_200_OK)'''


'''@csrf_exempt
def message_list(request):
    """
    List all messages, or create a new message.
    """
    if request.method == 'GET':
        return JsonResponse(dumps(list(messagesCollection.find({'name':'Shannon Brown'}))), safe=False)

    elif request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = SnippetSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(dumps(list(messagesCollection.find({'name':'Shannon Brown'}))),status=201)
        return JsonResponse("Error", status=400)'''

challenge2/restFramework/views.py
from django.shortcuts import render
from rest_framework import status, views
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import serializers
from rest_framework.decorators import api_view

# Create your views here.
class getStuffFromCollection(APIView):
    def get(self, request, format=None):
        myclient = pymongo.MongoClient("mongodb://localhost:27017/")
        mydb = myclient["test"]
        mycol = mydb["messages"]
        x = mycol.find_one()
        return Response({'message':x}, status=status.HTTP_200_OK)

challenge2/chat/templates/chat/create.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <style media="screen">
      @import url(https://fonts.googleapis.com/css?family=Roboto:300);
      h1 {
        color: #7F7FD5;
      }

    .login-page {
    width: 360px;
    padding: 8% 0 0;
    margin: auto;
    }
    .form {
    position: relative;
    z-index: 1;
    background: #FFFFFF;
    max-width: 360px;
    margin: 0 auto 100px;
    padding: 45px;
    text-align: center;
    box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
    }
    .form input {
    font-family: "Roboto", sans-serif;
    outline: 0;
    background: #f2f2f2;
    width: 100%;
    border: 0;
    margin: 0 0 15px;
    padding: 15px;
    box-sizing: border-box;
    font-size: 14px;
    }
    .form button {
    font-family: "Roboto", sans-serif;
    text-transform: uppercase;
    outline: 0;
    background: #7F7FD5;
    width: 100%;
    border: 0;
    padding: 15px;
    color: #FFFFFF;
    font-size: 14px;
    -webkit-transition: all 0.3 ease;
    transition: all 0.3 ease;
    cursor: pointer;
    }
    .form button:hover,.form button:active,.form button:focus {
    background: #7F7FD5;
    }
    .form .message {
    margin: 15px 0 0;
    color: #7F7FD5;
    font-size: 12px;
    }
    .form .message a {
    color: #7F7FD5;
    text-decoration: none;
    }
    .form .register-form {
    display: none;
    }
    .container {
    position: relative;
    z-index: 1;
    max-width: 300px;
    margin: 0 auto;
    }
    .container:before, .container:after {
    content: "";
    display: block;
    clear: both;
    }
    .container .info {
    margin: 50px auto;
    text-align: center;
    }
    .container .info h1 {
    margin: 0 0 15px;
    padding: 0;
    font-size: 36px;
    font-weight: 300;
    color: #1a1a1a;
    }
    .container .info span {
    color: #4d4d4d;
    font-size: 12px;
    }
    .container .info span a {
    color: #000000;
    text-decoration: none;
    }
    .container .info span .fa {
    color: #EF3B3A;
    }
    body {
    background: #7F7FD5; /* fallback for old browsers */
    /*background: -webkit-linear-gradient(to right, #91EAE4, #86A8E7, #7F7FD5);
    background: -moz-linear-gradient(right, #76b852, #8DC26F);
    background: -o-linear-gradient(right, #76b852, #8DC26F);*/
    background: linear-gradient(to right, #91EAE4, #86A8E7, #7F7FD5);
    font-family: "Roboto", sans-serif;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    }
  </style>
  <body>
    <!--<a href="{% url 'chat:create' %}">Create Chat</a>-->
    <div class="login-page">
      <div class="form">
        <h1>Please enter a pin</h1>
        <form method="post" class="login-form">
          {% csrf_token %}
          {{form.pin}}
          <button>Create Chat</button>
          <p class="message">Already Have A Chat? <a href="{% url 'chat:index' %}">Enter Chat</a></p>
        </form>

        <!--<div class="login-page">
          <div class="form">
            <form class="register-form">
              <input type="text" placeholder="name"/>
              <input type="password" placeholder="password"/>
              <input type="text" placeholder="email address"/>
              <button>create</button>
              <p class="message">Already registered? <a href="#">Sign In</a></p>
            </form>
            <form class="login-form">
              <input type="text" placeholder="username"/>
              <input type="password" placeholder="password"/>
              <button>login</button>
              <p class="message">Not registered? <a href="#">Create an account</a></p>
            </form>
          </div>
        </div>-->
        <!--<form class="login-form">
          <input type="text" placeholder="username"/>
          <input type="password" placeholder="password"/>
          <button>login</button>
          <p class="message">Not registered? <a href="#">Create an account</a></p>
        </form>-->
      </div>
    </div>
  </body>


</html>

challenge2/chat/templates/chat/enter.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>{{ collection }}</h1>
  </body>
</html>

challenge2/chat/templates/chat/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <style media="screen">
      @import url(https://fonts.googleapis.com/css?family=Roboto:300);
      h1 {
        color: #7F7FD5;
      }

    .login-page {
    width: 360px;
    padding: 8% 0 0;
    margin: auto;
    }
    .form {
    position: relative;
    z-index: 1;
    background: #FFFFFF;
    max-width: 360px;
    margin: 0 auto 100px;
    padding: 45px;
    text-align: center;
    box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
    }
    .form input {
    font-family: "Roboto", sans-serif;
    outline: 0;
    background: #f2f2f2;
    width: 100%;
    border: 0;
    margin: 0 0 15px;
    padding: 15px;
    box-sizing: border-box;
    font-size: 14px;
    }
    .form button {
    font-family: "Roboto", sans-serif;
    text-transform: uppercase;
    outline: 0;
    background: #7F7FD5;
    width: 100%;
    border: 0;
    padding: 15px;
    color: #FFFFFF;
    font-size: 14px;
    -webkit-transition: all 0.3 ease;
    transition: all 0.3 ease;
    cursor: pointer;
    }
    .form button:hover,.form button:active,.form button:focus {
    background: #7F7FD5;
    }
    .form .message {
    margin: 15px 0 0;
    color: #7F7FD5;
    font-size: 12px;
    }
    .form .message a {
    color: #7F7FD5;
    text-decoration: none;
    }
    .form .register-form {
    display: none;
    }
    .container {
    position: relative;
    z-index: 1;
    max-width: 300px;
    margin: 0 auto;
    }
    .container:before, .container:after {
    content: "";
    display: block;
    clear: both;
    }
    .container .info {
    margin: 50px auto;
    text-align: center;
    }
    .container .info h1 {
    margin: 0 0 15px;
    padding: 0;
    font-size: 36px;
    font-weight: 300;
    color: #1a1a1a;
    }
    .container .info span {
    color: #4d4d4d;
    font-size: 12px;
    }
    .container .info span a {
    color: #000000;
    text-decoration: none;
    }
    .container .info span .fa {
    color: #EF3B3A;
    }
    body {
    background: #7F7FD5; /* fallback for old browsers */
    /*background: -webkit-linear-gradient(to right, #91EAE4, #86A8E7, #7F7FD5);
    background: -moz-linear-gradient(right, #76b852, #8DC26F);
    background: -o-linear-gradient(right, #76b852, #8DC26F);*/
    background: linear-gradient(to right, #91EAE4, #86A8E7, #7F7FD5);
    font-family: "Roboto", sans-serif;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    }
  </style>
  <body>
    <!--<a href="{% url 'chat:create' %}">Create Chat</a>-->
    <div class="login-page">
      <div class="form">
        <h1>Please enter a pin</h1>
        <form method="post" class="login-form">
          {% csrf_token %}
          {{form.pin}}
          <button>Enter Chat!</button>
          <p class="message">No Chat Room? <a href="{% url 'chat:create' %}">Let's Create One</a></p>
        </form>

        <!--<div class="login-page">
          <div class="form">
            <form class="register-form">
              <input type="text" placeholder="name"/>
              <input type="password" placeholder="password"/>
              <input type="text" placeholder="email address"/>
              <button>create</button>
              <p class="message">Already registered? <a href="#">Sign In</a></p>
            </form>
            <form class="login-form">
              <input type="text" placeholder="username"/>
              <input type="password" placeholder="password"/>
              <button>login</button>
              <p class="message">Not registered? <a href="#">Create an account</a></p>
            </form>
          </div>
        </div>-->
        <!--<form class="login-form">
          <input type="text" placeholder="username"/>
          <input type="password" placeholder="password"/>
          <button>login</button>
          <p class="message">Not registered? <a href="#">Create an account</a></p>
        </form>-->
      </div>
    </div>
  </body>


</html>

challenge2/chat/templates/chat/message_list.html
<html><body>
<h1>Profiles</h1>
<ul>
    {% for message in messages %}
    <li>{{ message.message }}</li>
    {% endfor %}
</ul>
</body></html>

challenge2/chat/templates/chat/room.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <title>Chat</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.js"></script>
  </head>
  <style media="screen">
    body,html{
    height: 100%;
    margin: 0;
    background: #7F7FD5;
    background: -webkit-linear-gradient(to right, #91EAE4, #86A8E7, #7F7FD5);
    background: linear-gradient(to right, #91EAE4, #86A8E7, #7F7FD5);
    }
    .card{
    height: 100%;
    border-radius: 15px !important;
    background-color: rgba(0,0,0,0.4) !important;
    margin: 15%;
    }
    .contacts_body{
    padding:  0.75rem 0 !important;
    overflow-y: auto;
    white-space: nowrap;
    }
    .msg_card_body{
    overflow-y: auto;
    }
    .card-header{
    border-radius: 15px 15px 0 0 !important;
    border-bottom: 0 !important;
    }
    .card-footer{
    border-radius: 0 0 15px 15px !important;
    border-top: 0 !important;
    }
    .container{
    align-content: center;
    }
    .search{
    border-radius: 15px 0 0 15px !important;
    background-color: rgba(0,0,0,0.3) !important;
    border:0 !important;
    color:white !important;
    }
    .search:focus{
    box-shadow:none !important;
    outline:0px !important;
    }
    .type_msg{
    background-color: rgba(0,0,0,0.3) !important;
    border:0 !important;
    color:white !important;
    height: 60px !important;
    overflow-y: auto;
    }
    .type_msg:focus{
    box-shadow:none !important;
    outline:0px !important;
    }
    .attach_btn{
    border-radius: 15px 0 0 15px !important;
    background-color: rgba(0,0,0,0.3) !important;
    border:0 !important;
    color: white !important;
    cursor: pointer;
    }
    .send_btn{
    border-radius: 0 15px 15px 0 !important;
    background-color: rgba(0,0,0,0.3) !important;
    border:0 !important;
    color: white !important;
    cursor: pointer;
    }
    .search_btn{
    border-radius: 0 15px 15px 0 !important;
    background-color: rgba(0,0,0,0.3) !important;
    border:0 !important;
    color: white !important;
    cursor: pointer;
    }
    .contacts{
    list-style: none;
    padding: 0;
    }
    .contacts li{
    width: 100% !important;
    padding: 5px 10px;
    margin-bottom: 15px !important;
    }
    .active{
    background-color: rgba(0,0,0,0.3);
    }
    .user_img{
    height: 70px;
    width: 70px;
    border:1.5px solid #f5f6fa;

    }
    .user_img_msg{
    height: 40px;
    width: 40px;
    border:1.5px solid #f5f6fa;

    }
    .img_cont{
    position: relative;
    height: 70px;
    width: 70px;
    }
    .img_cont_msg{
    height: 40px;
    width: 40px;
    }
    .online_icon{
    position: absolute;
    height: 15px;
    width:15px;
    background-color: #4cd137;
    border-radius: 50%;
    bottom: 0.2em;
    right: 0.4em;
    border:1.5px solid white;
    }
    .offline{
    background-color: #c23616 !important;
    }
    .user_info{
    margin-top: auto;
    margin-bottom: auto;
    margin-left: 15px;
    }
    .user_info span{
    font-size: 20px;
    color: white;
    }
    .user_info p{
    font-size: 10px;
    color: rgba(255,255,255,0.6);
    }
    .video_cam{
    margin-left: 50px;
    margin-top: 5px;
    }
    .video_cam span{
    color: white;
    font-size: 20px;
    cursor: pointer;
    margin-right: 20px;
    }
    .msg_cotainer{
    margin-top: auto;
    margin-bottom: auto;
    margin-left: 10px;
    border-radius: 25px;
    background-color: #82ccdd;
    padding: 10px;
    position: relative;
    }
    .msg_cotainer_send{
    margin-top: auto;
    margin-bottom: auto;
    margin-right: 20px;
    border-radius: 25px;
    background-color: #78e08f;
    padding: 10px;
    position: relative;
    }
    .msg_time{
    position: absolute;
    left: 0;
    bottom: -15px;
    color: rgba(255,255,255,0.5);
    font-size: 10px;
    width: 400px;
    }
    .justify-content-end .msg_time{
      right:0;
      text-align: right;
      left:auto !important;
    }
    .msg_time_send{
    position: absolute;
    right:0;
    bottom: -15px;
    color: rgba(255,255,255,0.5);
    font-size: 10px;
    }
    .msg_head{
    position: relative;
    }
    #action_menu_btn{
    position: absolute;
    right: 10px;
    top: 10px;
    color: white;
    cursor: pointer;
    font-size: 20px;
    }
    .action_menu{
    z-index: 1;
    position: absolute;
    padding: 15px 0;
    background-color: rgba(0,0,0,0.5);
    color: white;
    border-radius: 15px;
    top: 30px;
    right: 15px;
    display: none;
    }
    .action_menu ul{
    list-style: none;
    padding: 0;
    margin: 0;
    }
    .action_menu ul li{
    width: 100%;
    padding: 10px 15px;
    margin-bottom: 5px;
    }
    .action_menu ul li i{
    padding-right: 10px;

    }
    .action_menu ul li:hover{
    cursor: pointer;
    background-color: rgba(0,0,0,0.2);
    }
    @media(max-width: 576px){
    .contacts_card{
    margin-bottom: 15px !important;
    }
    }
    #scrollDiv{
      max-height: calc(100% - 170px);
    }
  </style>

  <body>
    <div class="container-fluid h-100">
			<div class="row justify-content-center h-100">
				<div class="col-md-12 col-xl-12 chat h-100">
					<div class="card">
						<div class="card-header msg_head">
							<div class="d-flex bd-highlight">
								<div class="user_info">
									<span>{{name}}</span>
									<p>{{COUNTOFMESSAGES}} Messages</p>
								</div>
								<div class="video_cam">
								</div>
							</div>
							<span id="action_menu_btn"><i class="fas fa-ellipsis-v"></i></span>
							<div class="action_menu">
								<ul>
									<li><i class="fas fa-user-circle"></i> View profile</li>
									<li><i class="fas fa-users"></i> Add to close friends</li>
									<li><i class="fas fa-plus"></i> Add to group</li>
									<li><i class="fas fa-ban"></i> Block</li>
								</ul>
							</div>
						</div>
						<div id="scrollDiv" class="card-body msg_card_body">


						</div>
						<div class="card-footer">
							<div class="input-group">
								<div class="input-group-append">
									<span class="input-group-text attach_btn"></span>
								</div>
								<textarea id="messageText" name="" class="form-control type_msg" placeholder="Type your message..."></textarea>
								<div class="input-group-append">
                  <input class="type_msg"type="text" name="username" value="" placeholder="Username" id="username">
									<span id="formSubmit" class="input-group-text send_btn"><i class="fas fa-location-arrow"></i></span>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>






    <script>
      $( document ).ready(function() {

        $("#formSubmit").click(function() {
          console.log("I got here");
          $.ajax({
            async: true,
            type: "POST",
            url: "http://localhost:8000/chat/getStuffFromCollection/",
            data: {
              "name": $("#username").val(),
              "message": $("#messageText").val(),
              "timestamp": new Date(),
              "room": "{{id}}",
            },
            success: {function(data) {
              console.log("Success");
            }},
            dataType: 'json'
          });

        })
        setInterval(function(){
          console.log("let's do it");
          $.ajax({
            async: true,
            type: "GET",
            url: "http://localhost:8000/chat/getStuffFromCollection/",
            data: {
              "room": "{{id}}",
            },
            success: function(data) {
              console.log("succeeded!!");
              $("#scrollDiv").empty();
              var i;
              for (i = 0; i < data.thingINeed.length; i++) {
                if(data.thingINeed[i].name == $('#username').val()){
                  $("#scrollDiv").append('<div class="d-flex justify-content-end mb-4"><div class="msg_cotainer_send">' + data.thingINeed[i].message + '<span class="msg_time">'+data.thingINeed[i].name+" - " + data.thingINeed[i].timestamp + '</span></div></div>');
                } else{
                    $("#scrollDiv").append('<div class="d-flex justify-content-start mb-4"><div class="msg_cotainer">' + data.thingINeed[i].message + '<span class="msg_time">'+data.thingINeed[i].name+" - " + data.thingINeed[i].timestamp + '</span></div></div>');
                }

              }
              $('#scrollDiv').scrollTop($('#scrollDiv')[0].scrollHeight);
            },
            dataType: 'json'
          });

        }, 1000);
      });
    </script>

    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  </body>
</html>